[package]
name = "atlantic-sdk"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
thiserror = { workspace = true }
url = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
