codecov:
  notify:
    wait_for_ci: true

coverage:
  status:
    project: #add everything under here, more options at https://docs.codecov.com/docs/commit-status
      # default does not cascade down to projects
      # we add a threshold of 2% as hypothesis fuzzing creates some noise on indirect changes
      default:
        target: auto
        threshold: 2%
      ethereum:
        paths:
          - cairo/ethereum
        target: auto
        threshold: 2%
      ethereum_rlp:
        paths:
          - cairo/ethereum_rlp
        target: auto
        threshold: 2%
      ethereum_types:
        paths:
          - cairo/ethereum_types
        target: auto
        threshold: 2%
      cairo_addons:
        paths:
          - python/cairo-addons
        target: auto
        threshold: 2%
      cairo_ec:
        paths:
          - python/cairo-ec
        target: auto
        threshold: 2%
      cairo_core:
        paths:
          - python/cairo-core
        target: auto
        threshold: 2%
      mpt:
        paths:
          - python/mpt
        target: auto
        threshold: 2%
    patch:
      default:
        target: 90%
        threshold: 0%
