name: Trunk Code Quality setup
description: Set up dependencies for Trunk Code Quality

runs:
  using: composite
  steps:
    - run: rustup update
      shell: bash

    - name: Rust cache
      uses: Swatinem/rust-cache@v2
      with:
        cache-on-failure: "true"

    - name: Setup uv
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: Create venv
      shell: bash
      run: |
        uv venv
        echo "$PWD/.venv/bin" >> $GITHUB_PATH

    - name: Install cairo-lint
      shell: bash
      run: uv sync --package cairo-lint

    - name: Install dependencies
      shell: bash
      run: uv pip install cairo-lang sympy

    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@v1
